version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key
      - ALLOWED_HOSTS=your-domain.com,www.your-domain.com
