version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - SECRET_KEY="django-insecure-8(6ko5+&&jw)iyw@(wxip$+9zd8^h8x54rr8!i&$q80sb&%ep0"
      - ALLOWED_HOSTS=3.142.130.57,your-domain.com,www.your-domain.com,
